### ISSUE TITLE
V5-docker-image SRID variable not respected

### ISSUE THREAD

**Issue by Crismon96** [3dcitydb/3dcitydb#259]
When I use the latest v5 docker image to create my 3dcitydb:

https://hub.docker.com/r/3dcitydb/3dcitydb-pg

with this configuration:

```
  citydb:
    image: 3dcitydb/3dcitydb-pg:edge
    container_name: citydb-container
    ports:
      - '5434:5432'
    environment:
      # Required
      - POSTGRES_PASSWORD=changeMe!
      - POSTGRES_USER=postgres
      # 3DCityDB specific settings
      - CITYDBNAME=postgres # Name of the 3DCityDB database
      - SRID=4326 # WGS84 - World Geodetic System 1984 (longitude/latitude)
      - SRSNAME=urn:ogc:def:crs:EPSG::4326 # WGS84 coordinate system name
    volumes:
      - citydb_data:/var/lib/postgresql/data
    restart: unless-stopped
```

I am expecting the specifiec long/lat coordinate system.
When I then import my buildings via the 3dcitydb-tool I also get the following logs:

```
[12:40:39 INFO] Connection: postgres@citydb:5432/postgres
[12:40:39 INFO] Schema: citydb
[12:40:39 INFO] SRID: 4326
[12:40:39 INFO] SRS name: WGS 84
[12:40:39 INFO] SRS URI: urn:ogc:def:crs,crs:EPSG::4326,crs:EPSG::4326
[12:40:39 INFO] Database indexes are on.
[12:40:39 INFO] [1|1] Importing file /data/seed/citydb-3d-building-models.gml.
```

Yet my geometry data is still in the default coordinate system:

e.g.

```
MULTIPOLYGON Z(((686474.909 5339400.175 517.5, 686480.431 5339401.53 517.5, 686479.121 5339407.113 513.564, 686473.598 5339405.758 513.564, 686474.909 5339400.175 517.5)))
```
no lat/long coordinate system.
