### ISSUE TITLE
3DCityDB Docker Healthcheck

### ISSUE THREAD

**Issue by BWibo** [3dcitydb/3dcitydb#69]
Docker can test if a container is still working using [healthchecks](https://docs.docker.com/engine/reference/builder/#healthcheck). This is especially important when orchestrating services and one services depends on a functional state of another services, like for instance the WFS requires an operational 3DCityDB instance.

Here is an example for a PostgresDB:
```yml

# ...
# ...

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 30s

# ...
# ...
```

For the 3DCityDB this means, that:

- The Postgres/Oracle DB inside the container is up and running
- The 3DCityDB Schema setup has completed

The second point leads to my question. At which point can I safely assume that 3DCityDB schema is fully set up. In the install script, the last operation (for Postgres) is to set the search path:
https://github.com/3dcitydb/3dcitydb/blob/20e1d0ab4c9c5d27461a40fbf73025a5ac7aa4b1/postgresql/SQLScripts/CREATE_DB.sql#L89
 Do you think checking for the correct `search_path` is suitable as a heathcheck test?
 
 ```bash
 psql -U postgres -d postgres -c 'show search_path;' | grep -q "citydb"
```
